### PR TITLE
CSV output changed to better match Gentle output

### PR DESCRIPTION
**Pull request by seanth**
Gentle(https://github.com/lowerquality/gentle) can generate a csv of word-by-word time stamps using a transcript and an audio file. Since Whisper makes the transcript AND can give timestamps per word, Whisper is basically a drop in replacement (and doesn't rely on getting the transcript from some other source first).

Changes to write_csv_words now outputs the csv in a format that is nearly identical to what Gentle outputs. I'm now using it in my projects that had relied on Gentle/Kaldi

### CODE REVIEW

**Comment by Jeronymous** [comment]
You're back! Thank you @seanth 
I'm merging this PR, and will make slight modification:
- make the csv file with suffix "*.words.csv"
- make `--csv` option False by default (to be closer to what Whisper does)
- use python `csv` lib to write th csv (note: before this modification, there was a problem when there was "," in the text, conflicting with the coma in the csv, that's why it's always better to use dedicated lib to write csv rather than to do it "by hand")

**Comment by Jeronymous** [comment]
Done: https://github.com/Jeronymous/whisper-timestamped/commit/82bf900270c90b38a79ab46691366e6adb448808#diff-4d4adecf50ce8affc04f13ab7274717945dd716eb910225ff154f717e81c3b64

Concerning removing the punctuation from the words, I'm thinking that I should do that as a option (commonly for all the formats, not just the CSV).

Are you OK with that?
You would have to opt in for some option to have that from the CLI

**Comment by Jeronymous** [comment]
Implemented: https://github.com/Jeronymous/whisper-timestamped/commit/1e906c0d53ad9bb5e4da1574b363d8eca58ac300

So in the end, if using the master branch, you should now use
```
--csv True --punctuations False
```

**Comment by seanth** [comment]
Late to the party, but I think having a CLI option to keep or remove punctuation is a great idea. ++

**Pull request merged**
